[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 8MB

lib_deps = 
	fastled/FastLED@^3.10.3
	olikraus/U8g2@^2.36.18
	z3t0/IRremote@^4.4.1
